food/urls.py
from . import views
from django.urls import path

app_name = 'food'
urlpatterns = [
    #/food/
    path('', views.IndexClassView.as_view(), name= 'index'),
    #/food/1
    path('<int:pk>/',views.FoodDetailView.as_view(),name='detail'),
    path ('item/', views.item,name='item'),
    #add items
    path('add/',views.CreateItem.as_view(), name='create_item'),
    #edit
    path('update/<int:id>/', views.update_item, name='update_item'),
    #delete
    path('delete/<int:id>/', views.delete_item, name= 'delete_item'),
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import include,path
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')), 
    path('register/', user_views.register, name='register'),
    path('login/', authentication_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profilepage, name='profile'),
]



urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Item(models.Model):

    def __str__(self):
        return self.item_name

    user_name = models.ForeignKey(User, on_delete=models.CASCADE,default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500,default="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTg1fVKRv4HsD3ESQtMcrv5u6ZcM9socXpQrUKSyh_E-NckPTmXF5RL7hg-M364_rehkPg&usqp=CAU")

    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})
    

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price','item_image']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisteForm(UserCreationForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

food/views.py
from django.forms.models import BaseModelForm
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

# Create your views here.

# def index(req):
#     item_list = Item.objects.all()
#     # template = loader.get_template('food/index.html')
#     context = {
#         'item_list': item_list,
#     }
#     # return HttpResponse(template.render(context,req))
#     # Alternative way below
#     return render(req,'food/index.html',context)


class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'





def item(req):
    return HttpResponse('<h1>This is an item view</h1>')

# def detail(req,item_id):
#     item = Item.objects.get(pk=item_id)
#     context = {
#         'item':item
#     }
#     return render(req,'food/detail.html',context)

class FoodDetailView(DetailView):
    model = Item
    template_name = "food/detail.html"
    


def create_item(req):
    form = ItemForm(req.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(req, 'food/item-form.html', {'form':form})

# classbased view for create item
class CreateItem(CreateView):
    model = Item
    fields = ['item_name','item_desc','item_price','item_image']
    template_name = "food/item-form.html"

    def form_valid(self, form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)


def update_item(req, id):
    item = Item.objects.get(id=id)
    form = ItemForm(req.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(req,'food/item-form.html',{'form':form,'item':item})

def delete_item(req, id):
    item = Item.objects.get(id=id)

    if  req.method == 'POST':
       item.delete()
       return redirect('food:index')
    
    return render(req,'food/item-delete.html',{'item':item}) 

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import RegisteForm

# Create your views here.

def register(req):
    if req.method == 'POST':
        form = RegisteForm(req.POST)
        if form.is_valid():
           form.save()
           username = form.cleaned_data.get('username')
           messages.success(req,f'Welcome {username}, your are currently logged in!')
           return redirect('login')
    else:
        form = RegisteForm()
    return render(req, 'users/register.html', {'form':form})

@login_required
def profilepage(req):
    return render (req, 'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <title>FoodApp</title>
</head>
<body>

    <nav class="navbar navbar-dark bg-dark">
        <div class="container-fluid"></div>
            <a class="navbar-brand  ms-4" href="/food/">FoodApp</a>
        
        <div class="navbar-button-group">
            <a class="btn btn-sm btn-outline-secondary pr-2" href="{% url 'food:create_item' %}">Add Item</a>
            <a class="btn btn-sm btn-outline-secondary pr-2" href="#">Delete Item</a>
            <a class="btn btn-sm btn-outline-secondary me-4" href="#">View Item</a>
            {% if user.is_authenticated %}
                <a class="btn btn-sm btn-outline-secondary pr-2" href="{% url 'profile' %}">Profile</a>
                <a class="btn btn-sm btn-outline-secondary pr-2" href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a class="btn btn-sm btn-outline-secondary pr-2" href="{% url 'login' %}">Login</a>
            {% endif %}
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{message}}
        </div>
            
        {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock%}
    
</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}

{%block body%}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img class="img-fluid item-image card" src="{{ item.item_image }}">
        </div>

        <div class="col-md-6">  
            <br>     
            <h1>{{ object.item_name }}</h1>
            <h2>{{ object.item_desc }}</h2>
            <h3>${{ object.item_price }}</h3>
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'food:delete_item' item.id %}">Delete</a>
        </div>

    </div>
</div>


{%endblock%}

food/templates/food/index.html
 {% extends 'food/base.html' %}
 {% block body %}

    <div class="container">
        {% for item in item_list %}
            <div class="row">
                <div class="col-md-3 item-container">
                    <img class="img-fluid item-image" src="{{ item.item_image }}" alt="">
                </div>
                <div class="col-md-6">
                    <br>
                    <h3>{{ item.item_name }}</h3>
                    <h5>{{ item.item_desc }}</h5>
                    <h6>${{ item.item_price }}</h6>
                    <h6>Item Added by: {{ item.user_name }}</h6>
                </div>
                <div class="col-md-3">
                    <br>
                    <a class="btn btn-success" href="{% url 'food:detail' item.id %}">Details</a>
                </div>

            </div>
        {% endfor %}
    </div>

 {% endblock %}
 

food/templates/food/item-delete.html
{% extends 'food/base.html' %}
{% block body %}

<form method="POST" action="">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ item.item_name }}?</h2>
    <button class="btn btn-success" type="submit">Confirm</button>
</form>

{% endblock %}

food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}


<div class="container">
    <div class="col-md-6">
      <div class="card shadow-lg">
        <div class="card-header bg-primary text-white text-center">
          <h4>Add Item</h4>
        </div>
        <div class="card-body">
          <form method="POST" enctype="multipart/form-data" class="needs-validation" novalidate>
            {% csrf_token %}
            <div class="row mb-3">
              <label for="{{ form.item_name.id_for_label }}" class="col-sm-4 col-form-label text-end">Item Name:</label>
              <div class="col-sm-8">
                {{ form.item_name }}
              </div>
            </div>
            <div class="row mb-3">
              <label for="{{ form.item_desc.id_for_label }}" class="col-sm-4 col-form-label text-end">Item Description:</label>
              <div class="col-sm-8">
                {{ form.item_desc }}
              </div>
            </div>
            <div class="row mb-3">
              <label for="{{ form.item_price.id_for_label }}" class="col-sm-4 col-form-label text-end">Item Price:</label>
              <div class="col-sm-8">
                {{ form.item_price }}
              </div>
            </div>
            <div class="row mb-3">
              <label for="{{ form.item_image.id_for_label }}" class="col-sm-4 col-form-label text-end">Item Image:</label>
              <div class="col-sm-8">
                {{ form.item_image }}
              </div>
            </div>
            <div class="text-center mt-3">
              <button class="btn btn-primary btn-block" type="submit">Save</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>


{% comment %} <form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">Save</button>

</form> {% endcomment %}
{% endblock %}

users/templates/users/login.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card shadow-lg">
          <div class="card-header bg-primary text-white text-center">
            <h4>Login</h4>
          </div>
          <div class="card-body d-flex flex-column align-items-center">
            <form method="POST" class="needs-validation" novalidate>
              {% csrf_token %}
              <div class="mb-3 text-center">
                <label for="{{ form.username.id_for_label }}" class="form-label">{{ form.username.label }}:</label>
                {{ form.username }}
              </div>
              <div class="mb-3 text-center">
                <label for="{{ form.password.id_for_label }}" class="form-label">{{ form.password.label }}:</label>
                {{ form.password }}
              </div>
              <div class="text-center mt-3">
                <button class="btn btn-primary btn-block" type="submit">Login</button>
              </div>
            </form>
          </div>
          <div class="card-footer bg-light text-center">
            Don't have an account? <a href="/register/">Sign up</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  

{% endblock %}


<!-- <form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Login</button>
</form> -->

users/templates/users/logout.html
<h1>You have been logged out</h1>

users/templates/users/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
    <h1>{{ user.username }}</h1>
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <img class="img-fluid" src="{{ user.profile.image.url }}">
            </div>
        </div>
    </div>
</body>
</html>

users/templates/users/register.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container d-flex align-items-center justify-content-center vh-100">
  <div class="col-md-6">
    <div class="card shadow-lg">
      <div class="card-header bg-primary text-white text-center">
        <h4>Sign Up</h4>
      </div>
      <div class="card-body">
        <form method="POST" class="needs-validation" novalidate>
          {% csrf_token %}
          <div class="row mb-3">
            <label for="{{ form.username.id_for_label }}" class="col-sm-4 col-form-label text-end">Username:</label>
            <div class="col-sm-8">
              {{ form.username }}
            </div>
          </div>
          <div class="row mb-3">
            <label for="{{ form.email.id_for_label }}" class="col-sm-4 col-form-label text-end">Email:</label>
            <div class="col-sm-8">
              {{ form.email }}
            </div>
          </div>
          <div class="row mb-3">
            <label for="{{ form.password1.id_for_label }}" class="col-sm-4 col-form-label text-end">Password:</label>
            <div class="col-sm-8">
              {{ form.password1 }}
            </div>
          </div>
          <div class="row mb-3">
            <label for="{{ form.password2.id_for_label }}" class="col-sm-4 col-form-label text-end">Confirm Password:</label>
            <div class="col-sm-8">
              {{ form.password2 }}
            </div>
          </div>
          <div class="text-center mt-3">
            <button class="btn btn-primary btn-block" type="submit">Sign Up</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}




















{% comment %} <form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">SignUp</button>

</form> {% endcomment %}